name: myworkflow
on:
  push:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      - name: step1
        run: echo this is step1
      - name: step2
        run: |
          echo this
          echo is
          echo step2
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: step1 of job2
        run: echo this is step1 of job2
      - name: step2
        run: |
          echo this
          echo is
          echo step2
          echo of
          echo job2
